name: Dev theme deploy

on:
  push:
    branches:
      - develop
jobs:
  deploy:
    name: Deploy Dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler: 'latest'
      - name: Install Shopify CLI
        run: npm install -g @shopify/cli@3.64.1 @shopify/theme@3.58.2
      - name: Install Dev Dependencies
        run: npm install
      - name: Build Output Dev
        run: npm run build
      - name: Deploy To Dev
        env:
          SHOPIFY_FLAG_STORE: ${{ secrets.SHOPIFY_STORE_URL_DEV }}
          SHOPIFY_CLI_THEME_TOKEN: ${{ secrets.SHOPIFY_CLI_THEME_TOKEN }}
          SHOPIFY_CLI_STACKTRACE: 1
        run: |
          cd shopifytheme 
          shopify theme push --ignore templates/* --ignore config/* --ignore snippets/*.json --ignore sections/*.json --ignore locales/* --allow-live --live 